version: "3.9"

services:

  database:
    image: "postgres:14"
    ports:
      - "5432:5432"
    env_file:
      .env

  ubicor_api:
    build: .
    depends_on:
      - database
    ports:
      - "80:80"
