"""add priority order to building image

Revision ID: 5d3a1c80c7a2
Revises: f8ed083eed8a
Create Date: 2022-05-08 22:21:01.475394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3a1c80c7a2'
down_revision = 'f8ed083eed8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings_images', sa.Column('priority_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings_images', 'priority_order')
    # ### end Alembic commands ###
