"""add_provider_to_user

Revision ID: 96878da78c67
Revises: 5ce4505fe060
Create Date: 2022-07-09 20:44:36.206988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96878da78c67'
down_revision = '5ce4505fe060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
