"""add building zone

Revision ID: 9c68eacd67f1
Revises: 5d3a1c80c7a2
Create Date: 2022-05-21 14:49:18.679653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c68eacd67f1'
down_revision = '5d3a1c80c7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_zones',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_building_zones_name'), 'building_zones', ['name'], unique=False)
    op.add_column('buildings', sa.Column('zone', sa.String(), nullable=True))
    op.create_foreign_key(None, 'buildings', 'building_zones', ['zone'], ['name'])
    op.drop_constraint('universities_slug_key', 'universities', type_='unique')
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.create_unique_constraint('universities_slug_key', 'universities', ['slug'])
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'zone')
    op.drop_index(op.f('ix_building_zones_name'), table_name='building_zones')
    op.drop_table('building_zones')
    # ### end Alembic commands ###
