"""add is_active to building

Revision ID: f0855e19362c
Revises: e3350f532423
Create Date: 2022-05-08 14:27:47.868833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0855e19362c'
down_revision = 'e3350f532423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'universities', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='unique')
    op.drop_column('buildings', 'is_active')
    # ### end Alembic commands ###
