name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sh scripts.sh publish
    - name: Reload server
      run: |
        echo ${{AMAZON_SERVER_KEY}} > server-key.pem
        sh scripts.sh deploy
