name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{secrets.DOCKER_PASSWORD}}" | docker login --username ${{secrets.DOCKER_USER}} --password-stdin
        sh scripts.sh publish
    - name: Reload server
      run: |
        echo "${{secrets.AMAZON_SERVER_KEY}}" > server-key.pem
        sh scripts.sh deploy
